SNARETree = {'Qa': {'Qa.I': {'Qa.I.Syx18': {"Qa.I.Syx18.Metazoa": '',
											"Qa.I.Syx18.SAR": '',
											"Qa.I.Syx18.Viridiplantae": ''},
							 'Qa.I.Ufe1': ''},
					'Qa.II': {'Qa.II.Sed5': '',
							  'Qa.II.Syx5': {'Qa.II.Syx5.Metazoa': '',
											 'Qa.II.Syx5.SAR': '',
											 'Qa.II.Syx5.Viridiplantae': ''}},
					'Qa.III': {'Qa.III.a': '',
							   'Qa.III.b': ''},
					'Qa.IV': {'Qa.IV.Sso': '',
							  'Qa.IV.Syx': ''}},
			 'Qb': {'Qb.I': {'Qb.I.Metazoa': '',
							 'Qb.I.Viridiplantae': '',
							 'Qb.I.Fungi': ''},
					'Qb.II': {'Qb.II.Gos': {'Qb.II.Gos.Gos2': '',
											'Qb.II.Gos.Fungi': '',
											'Qb.II.Gos.Viridiplantae': ''},
							  'Qb.II.MemBos': {'Qb.II.MemBos.Bos1': '',
											   'Qb.II.MemBos.Membrin': ''}},
					'Qb.III': {'Qb.III.b': {'Qb.III.b.Metazoa': '',
											'Qb.III.b.SAR': '',
											'Qb.III.b.Viridiplantae': '',
											'Qb.III.b.Fungi': ''},
							   'Qb.III.d': ''}},
			 'Qc': {'Qc.I': {'Qc.I.Fungi': '',
							 'Qc.I.Metazoa': '',
							 'Qc.I.Viridiplantae': ''},
					'Qc.II': {'Qc.II.Bet1': '',
							  'Qc.II.Sft1': ''},
					'Qc.III': {'Qc.III.b': {'Qc.III.b.Fungi': '',
											'Qc.III.b.Metazoa': '',
											'Qc.III.b.Syp7': ''},
							   'Qc.III.c': {'Qc.III.c.Syp5': '',
											'Qc.III.c.Syx8': '',
											'Qc.III.c.Vam7': ''}}},
			 'R': {'R.I': {'R.I.Fungi': '',
						   'R.I.Metazoa': '',
						   'R.I.Viridiplantae': ''},
				   'R.II': '',
				   'R.III': {'R.III.Nyv1': '',
							 'R.III.Vamp7': '',
							 'R.III.Vamp4': '',
							 'R.III.Endob': ''},
				   'R.IV': {'R.IV.Fungi': '',
							'R.IV.Metazoa': ''},
				   'R.Reg': {'R.Reg.Fungi': '',
							 'R.Reg.Metazoa': '',
							 'R.Reg.Viridiplantae': ''}},
			 'SNAP': {'SNAP.b': {'SNAP.b.Sec9': '',
								 'SNAP.b.SN25': '',
								 'SNAP.b.SN29': ''},
					  'SNAP.c': {'SNAP.c.Sec9': '',
								 'SNAP.c.SN25': '',
								 'SNAP.c.SN29': ''}}
			 }


# Habc classification is not yet trained (see generateStatisticalHmmModels.py); this tree is a
# placeholder for that future work. Merged from the formerly-duplicate utils/hmmNames.py, which
# had a more granular breakdown (taxonomic subdivisions) than the tree previously defined here;
# 'Membos' was renamed to 'MemBos' to match the SNARE-side naming convention (c.f. Qb.II.MemBos).
HabcTree = {'Ha': {'Ha.I': {'Ha.I.Syx18': {'Ha.I.Syx18.Metazoa': '',
											'Ha.I.Syx18.Viridiplantae': ''},
							 'Ha.I.Ufe1': ''},
					'Ha.II': '',
					'Ha.III': {'Ha.III.a': '',
							   'Ha.III.b': {'Ha.III.b.Syx17': '',
											'Ha.III.b.Metazoa': '',
											'Ha.III.b.Viridiplantae': '',
											'Ha.III.b.Fungi': ''}},
					'Ha.IV': {'Ha.IV.Metazoa': '',
							  'Ha.IV.Sso': '',
							  'Ha.IV.Syx': '',
							  'Ha.IV.Syx1x': '',
							  'Ha.IV.Viridiplantae': ''}},
			 'Hb': {'Hb.I': {'Hb.I.fungi': '',
							 'Hb.I.metazoa': '',
							 'Hb.I.viridiplantae': ''},
					'Hb.II': {'Hb.II.Gos': {'Hb.II.Gos.fungi': '',
											 'Hb.II.Gos.zoophyta': ''},
							  'Hb.II.MemBos': {'Hb.II.MemBos.Bos1': '',
											   'Hb.II.MemBos.Membrin': ''}},
					'Hb.III': {'Hb.III.b': {'Hb.III.b.Vti1a': '',
											 'Hb.III.b.Vti1b': '',
											 'Hb.III.b.Vtifungi': '',
											 'Hb.III.b.Vtiviridiplantae': ''},
							   'Hb.III.d': ''}},
			 'Hc': {'Hc.I': {'Hc.I.Fungi': '',
							 'Hc.I.Metazoa': '',
							 'Hc.I.Viridiplantae': ''},
					'Hc.III': {'Hc.III.b': {'Hc.III.b.Metazoa': '',
											 'Hc.III.b.Fungi': ''},
							   'Hc.III.c': {'Hc.III.c.Vam7': '',
											'Hc.III.c.Fungi': '',
											'Hc.III.c.Metazoa': ''}}},
			 'Hr': {'Hr.I': '',
					'Hr.II': '',
					'Hr.III': ''}
			 }
